export const serviceContent = {
  en: {
    hero: 'Energetic and soul level support, but also in human thinking, feeling and acting',
    title: 'Services',
    description: 'Soulshine offers healing modalities with a variety of intensity.',
    counseling: 'Counseling & Therapy',
    counselingDescription: 'Psycho-therapist Sarah...',
    guidance: 'Spiritual Guidance',
    guidanceDescription: 'Spiritual Guidance...',
    ceremonies: 'Shamanic Healing Ceremonies',
    ceremoniesDescription: 'A healing ceremony...',
    integration: 'Medicine Integration Support',
    integrationDescription: 'Support with integrating experiences with plant medicines and spiritual experiences.',
    cacao: 'Cacao Meditations',
    cacaoDescription: 'The Soulshine community...',
    energy: 'International Energy Work',
    energyDescription: 'Energy block clearings, energy insights',
    matrimony: 'Shamanic Matrimony',
    matrimonyDescription: "Book Sarah",
    unsure: 'Not sure where to begin?',
    book: "Book a Consultation",
    explore: "Explore more",
    serviceList: [
        ['Counseling & Therapy', 'Psycho-therapist Sarah...'],
    ]
  },
  de: {
    hero: 'Energetic and soul level support, but also in human thinking, feeling and acting',
    title: 'Services',
    description: 'Soulshine offers healing modalities with a variety of intensity.',
    counseling: 'Counseling & Therapy',
    counselingDescription: 'Psycho-therapist Sarah...',
    guidance: 'Spiritual Guidance',
    guidanceDescription: 'Spiritual Guidance...',
    ceremonies: 'Shamanic Healing Ceremonies',
    ceremoniesDescription: 'A healing ceremony...',
    integration: 'Medicine Integration Support',
    integrationDescription: 'Support with integrating experiences with plant medicines and spiritual experiences.',
    cacao: 'Cacao Meditations',
    cacaoDescription: 'The Soulshine community...',
    energy: 'International Energy Work',
    energyDescription: 'Energy block clearings, energy insights',
    matrimony: 'Shamanic Matrimony',
    matrimonyDescription: "Book Sarah",
    unsure: 'Not sure where to begin?',
    book: "Book a Consultation",
    explore: "Explore more"
  },
};